# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'




## => Site Settings
##############################
text_skin: ocean # "default" (default), "dark", "forest", "ocean", "chocolate", "orange"
highlight_theme: default # "default" (default), "tomorrow", "tomorrow-night", "tomorrow-night-eighties", "tomorrow-night-blue", "tomorrow-night-bright"
url     : 
baseurl : # does not include hostname
title   : Purdue Lunabotics Wiki
description: > # this means to ignore newlines until "Language & timezone"
  Learn about the lunar robot we're building for NASA's Lunabotics competition

## => Language and Timezone
##############################
lang: # the language of your site, default as "en"
timezone: # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for the available values


## => Author and Social
##############################
author:
  type      : organization # "person" (default), "organization"
  name      : Purdue Lunabotics 
  url       : https://web.ics.purdue.edu/~lunabot
  avatar    : # path or url of avatar image (square)
  bio       : Each year we design, build, and code an autonomous mining robot from the ground up to compete in a NASA lunar-style mining compeition.
  email     : purduelunaboticsteam@gmail.com
  twitter   : PurdueLunabotic # "user_name" the last part of your profile url, e.g. https://twitter.com/user_name
  # linkedin  : # "user_name" the last part of your profile url, e.g. https://www.linkedin.com/in/user_name
  github    : PurdueLunabotics # "user_name" the last part of your profile url, e.g. https://github.com/user_name


## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: purdue-arc/wiki
repository_tree: master


## => Paths
##############################
paths:
  root    : # title link url, "/" (default)
  home    : # title link url, "/" (default)
  wiki    : # wiki layout url, "/" (default)
  rss     : # "/feed.xml" (default)


## => Post
##############################
## excerpt
excerpt_separator: <!--more-->

## license
license: CC-BY-NC-4.0 # "CC-BY-4.0", "CC-BY-SA-4.0", "CC-BY-NC-4.0", "CC-BY-ND-4.0"

## TOC
toc:
  selectors: # "h1,h2,h3" (default)


## => Markdown Enhancements
##############################
## Mathjax
mathjax: true # false (default), true
mathjax_autoNumber: # false (default), true

## Mermaid
mermaid: true #false (default), true

## Chart
chart: true # false (default), true


## => Paginate
##############################
paginate: 8
paginate_path: /page:num # don't change this unless for special need


## => Sources
##############################
sources: # bootcdn (default), unpkg


## => Sharing
##############################
sharing:
  provider: false # false (default), "addtoany", "addthis", "custom"

  ## AddThis
  addthis:
    id: # AddThis pubid, e.g. ra-5xxxxxxxxxxx


## => Comments
##############################
comments:
  provider: "gitalk" # false (default), "disqus", "gitalk", "valine", "custom"

  ## Gitalk
  gitalk:
    clientID    : "678ccd868e4bdc8e1843"
    clientSecret: "8e9a809afbecaf12bdce3e5a6f03e71f3e10c1ae" # GitHub Application Client Secret
    repository  : "wiki" # GitHub repo
    owner       : "PurdueLunabotics" # GitHub repo owner
    admin:
    - raghavauppuluri13

## => Pageview
##############################
pageview:
  provider: false # false (default), "leancloud", "custom"

  ## Leancloud
  leancloud:
    app_id    : # LeanCloud App id
    app_key   : # LeanCloud App key
    app_class : # LeanCloud App class


## => Search
##############################
search:
  provider: default # "default" (default), false, "google", "custom"

  ## Google Custom Search Engine
  google:
    custom_search_engine_id: # Google Custom Search Engine ID


## => Analytics
##############################
analytics:
  provider: # false (default), "google", "custom"

  ## Google Analytics
  google:
    tracking_id : "" # Google Analytics id for the site
    anonymize_ip:  # Anonymize IP tracking for Analytics


## => Build
##############################
markdown    : kramdown
highlighter : rouge
permalink   : date

exclude:
  - CHANGELOG.md
  - HOW_TO_RELEASE.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /node_modules
  - /vendor

collections_dir: wiki 
collections:
  wiki:
    output: true
    permalink: /:name


defaults:
  - scope:
      path: ""
    values:
      layout: article 
      pageview: false 
      sidebar:
        nav: wiki
      license: false 
      aside:
        toc: true
      show_edit_on_github: true
      show_date: true 
      lightbox: true

## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
